"""Authentication and security utilities for FinOpsia API."""
import base64
from datetime import datetime, timedelta
import hashlib
import hmac
import os
import secrets
from typing import Optional
from jose import JWTError, jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from src.core.env import load_project_env
from src.db.repositories import fetch_user_by_id

try:
    from passlib.context import CryptContext
except ImportError:  # pragma: no cover - fallback for minimal local environments
    CryptContext = None

load_project_env()

# Security configuration
SECRET_KEY = os.getenv("API_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("API_SECRET_KEY environment variable must be set")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
ADMIN_USER_IDS = {
    int(value.strip())
    for value in os.getenv("ADMIN_USER_IDS", "").split(",")
    if value.strip().isdigit()
}
ADMIN_USERNAMES = {
    value.strip()
    for value in os.getenv("ADMIN_USERNAMES", "").split(",")
    if value.strip()
}

# Password hashing context
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto") if CryptContext else None
security = HTTPBearer()
PBKDF2_ITERATIONS = 390000


class SecurityError(Exception):
    """Custom security exception."""
    pass


def hash_password(password: str) -> str:
    """Hash password using bcrypt."""
    if not password or len(password) < 8:
        raise ValueError("Password must be at least 8 characters")
    if pwd_context:
        return pwd_context.hash(password)
    return _hash_password_fallback(password)


def _hash_password_fallback(password: str) -> str:
    """Create a PBKDF2 password hash when passlib is unavailable."""
    salt = secrets.token_bytes(16)
    derived_key = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        PBKDF2_ITERATIONS,
    )
    encoded_salt = base64.b64encode(salt).decode("ascii")
    encoded_hash = base64.b64encode(derived_key).decode("ascii")
    return f"pbkdf2_sha256${PBKDF2_ITERATIONS}${encoded_salt}${encoded_hash}"


def _verify_password_fallback(plain_password: str, hashed_password: str) -> bool:
    """Verify PBKDF2 hashes generated by the local fallback."""
    try:
        scheme, iterations, encoded_salt, encoded_hash = hashed_password.split("$", 3)
        if scheme != "pbkdf2_sha256":
            return False
        salt = base64.b64decode(encoded_salt.encode("ascii"))
        expected_hash = base64.b64decode(encoded_hash.encode("ascii"))
        candidate_hash = hashlib.pbkdf2_hmac(
            "sha256",
            plain_password.encode("utf-8"),
            salt,
            int(iterations),
        )
        return hmac.compare_digest(candidate_hash, expected_hash)
    except Exception:
        return False


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify password against hash."""
    try:
        if hashed_password.startswith("pbkdf2_sha256$"):
            return _verify_password_fallback(plain_password, hashed_password)
        if not pwd_context:
            return False
        return pwd_context.verify(plain_password, hashed_password)
    except Exception:
        return False


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create JWT access token."""
    to_encode = data.copy()
    
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    
    to_encode.update({"exp": expire})
    
    try:
        encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
        return encoded_jwt
    except Exception as e:
        raise SecurityError(f"Failed to create token: {str(e)}")


def decode_token(token: str) -> dict:
    """Decode and validate JWT token."""
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid authentication credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        user_id = payload.get("sub")
        
        if user_id is None:
            raise credentials_exception
        
        return payload
        
    except JWTError:
        raise credentials_exception


async def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)) -> dict:
    """Get current user from JWT token."""
    token = credentials.credentials
    payload = decode_token(token)
    
    user_id = payload.get("sub")
    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token",
        )
    
    return {"user_id": int(user_id), "username": payload.get("username")}


async def get_current_admin(current_user: dict = Depends(get_current_user)) -> dict:
    """Verify current user is admin via server-side allowlist."""
    user = fetch_user_by_id(current_user["user_id"])
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
        )

    is_admin = (
        user.get("role") == "admin"
        or user["user_id"] in ADMIN_USER_IDS
        or user["username"] in ADMIN_USERNAMES
    )
    if not is_admin:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required",
        )

    return {
        "user_id": user["user_id"],
        "username": user["username"],
        "role": user.get("role", "user"),
        "is_admin": True,
    }


def verify_account_access(account_owner_id: int, current_user_id: int) -> bool:
    """Verify user has access to account."""
    return account_owner_id == current_user_id
